# __GAME_DISPLAY_NAME__

A blank AXE game scaffold generated by the devkit CLI.

This template is intentionally minimal. It gives agents and humans the expected
AXE project shape without assuming a specific genre yet. Devkit workflows like
Autoplayer and entity preview run from `axe`, so the project only keeps the
real game shell and content.

## Included Entry Points

- `src/main_desktop.cpp`

## Included Data

- starter runtime scene at `data/scenes/level_01.json`
- starter entity preview scene at `data/scenes/entity_preview.json`
- starter action manifest at `data/input_actions.json`
- starter Autoplayer smoke spec at `data/play_specs/smoke_test.json`
- placeholder reusable entity at `data/entities/example_entity.json`

## Project Layout

```text
__GAME_ID__/
|- assets/
|- artifacts/
|- data/
|  |- entities/
|  |- play_specs/
|  `- scenes/
|- scripts/
|- src/
|- vendor/
|- CMakeLists.txt
|- README.md
`- game.json
```

## Build

From this game folder:

```powershell
..\..\devkit\cli\axe.ps1 build --game . --config Debug
```

## Run

From this game folder:

```powershell
..\..\devkit\cli\axe.ps1 run --game . --config Debug
```

## Package

From this game folder:

```powershell
..\..\devkit\cli\axe.ps1 package --game . --config Debug --build-first
```

## Run Autoplayer

From this game folder:

```powershell
..\..\devkit\cli\axe.ps1 autoplay --game . `
  --play-spec data\play_specs\smoke_test.json `
  --input-actions data\input_actions.json `
  --artifacts artifacts\autoplayer\smoke_test
```

## Run Entity Preview

From this game folder:

```powershell
..\..\devkit\cli\axe.ps1 preview entity --game . `
  --entity data\entities\example_entity.json `
  --artifacts artifacts\entity_preview\example_entity
```

Next step:

- replace the placeholder entity with a real one
- add assets under `assets/`
- evolve the start scene into a real game scene
