# __GAME_DISPLAY_NAME__

A blank Autoplayer One game scaffold generated by the devkit CLI.

This template is intentionally minimal. It gives agents and humans the expected
Autoplayer One project shape without assuming a specific genre yet. Devkit workflows like
Autoplayer and entity preview run from `ap1`, so the project only keeps the
real game shell and content.

## Included Entry Points

- `src/main_desktop.cpp`

## Included Data

- starter runtime scene at `data/scenes/level_01.json`
- starter entity preview scene at `data/scenes/entity_preview.json`
- starter action manifest at `data/input_actions.json`
- starter Autoplayer smoke spec at `data/play_specs/smoke_test.json`
- placeholder reusable entity at `data/entities/example_entity.json`

Starter scenes include `layout.width`, `layout.height`, and `layout.origin` so
scene previews and placement work have a stable coordinate contract from the start.

## Project Layout

```text
__GAME_ID__/
|- assets/
|- .ap1/
|- data/
|  |- entities/
|  |- play_specs/
|  `- scenes/
|- scripts/
|  `- scenes/
|- src/
|- vendor/
|- CMakeLists.txt
|- README.md
`- game.json
```

## Build

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 build --game . --config Debug
```

## Run

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 run --game . --config Debug
```

## Package

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 package --game . --config Debug --build-first
```

## Run Autoplayer

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 autoplay --game . `
  --play-spec data\play_specs\smoke_test.json `
  --input-actions data\input_actions.json `
  --artifacts .ap1\autoplay\smoke_test
```

## Run Entity Preview

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 preview entity --game . `
  --entity data\entities\example_entity.json `
  --artifacts .ap1\entity_preview\example_entity
```

## Run Scene Preview

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 preview scene --game . `
  --scene data\scenes\level_01.json `
  --artifacts .ap1\scene_preview\level_01 `
  --hide-ui --show-layout
```

## Scaffold More Content

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 new entity enemy-chaser
..\..\gdk\cli\ap1.ps1 new scene room-02
..\..\gdk\cli\ap1.ps1 new spec room-02-smoke
```

When you run these inside the game folder, `ap1` uses the current directory automatically.
`new scene` also creates `scripts/scenes/<scene>.lua` as a scene-level logic stub.

Next step:

- replace the placeholder entity with a real one
- add assets under `assets/`
- evolve the start scene into a real game scene
