# __GAME_DISPLAY_NAME__

A blank Autoplayer One game scaffold generated by the devkit CLI.

This template is intentionally minimal. It gives agents and humans the expected
Autoplayer One project shape without assuming a specific genre yet. Devkit workflows like
Autoplayer and entity preview run from `ap1`, so the project only keeps the
real game shell and content.

## Included Entry Points

- `src/main_desktop.cpp`

## Included Data

- starter runtime scene at `scenes/level_01/level_01.json`
- starter entity preview scene at `scenes/entity_preview/entity_preview.json`
- starter action manifest at `data/input_actions.json`
- starter Autoplayer smoke spec at `scenes/level_01/specs/level_01-smoke.json`
- placeholder reusable entity at `entities/example_entity/example_entity.json`

Starter scenes include `layout.width`, `layout.height`, and `layout.origin` so
scene previews and placement work have a stable coordinate contract from the start.

## Project Layout

```text
__GAME_ID__/
|- assets/
|- .ap1/
|- data/
|- entities/
|  `- example_entity/
|- scenes/
|  |- entity_preview/
|  `- level_01/
|- scripts/
|  |- enemies/
|  |- player/
|  `- systems/
|- src/
|- vendor/
|- CMakeLists.txt
|- README.md
`- game.json
```

## Build

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 build --game . --config Debug
```

## Run

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 run --game . --config Debug
```

## Package

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 package --game . --config Debug --build-first
```

## Run Autoplayer

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 autoplay --game . `
  --play-spec scenes\level_01\specs\level_01-smoke.json `
  --input-actions data\input_actions.json `
  --artifacts .ap1\autoplay\smoke_test
```

## Run Entity Preview

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 preview entity --game . `
  --entity entities\example_entity\example_entity.json `
  --artifacts .ap1\entity_preview\example_entity
```

## Run Scene Preview

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 preview scene --game . `
  --scene scenes\level_01\level_01.json `
  --artifacts .ap1\scene_preview\level_01 `
  --hide-ui --show-layout
```

## Scaffold More Content

From this game folder:

```powershell
..\..\gdk\cli\ap1.ps1 new entity enemy-chaser
..\..\gdk\cli\ap1.ps1 new scene room-02
```

When you run these inside the game folder, `ap1` uses the current directory automatically.
`new scene` also creates:

- `scenes/<scene>/<scene>.lua`
- `scenes/<scene>/specs/<scene>-smoke.json`

Next step:

- replace the placeholder entity with a real one
- add assets under `assets/`
- evolve the start scene into a real game scene
